// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni

// SpeedtestSDKModel_Bridging_Header.h
// SpeedtestSDKModel_Bridging_Header

#import <Foundation/Foundation.h>

//! Project version number for SpeedtestSDKModelBridgingHeader.
FOUNDATION_EXPORT double SpeedtestSDKModelBridgingHeaderVersionNumber;

//! Project version string for SpeedtestSDKModelBridgingHeader.
FOUNDATION_EXPORT const unsigned char SpeedtestSDKModelBridgingHeaderVersionString[];

#import "STThroughputResult.h"
#import "STLatencyResult.h"
#import "STPacketlossResult.h"
#import "STTransferResult.h"
#import "STInterfaceInfo.h"
#import "STIpInfo.h"
#import "STServer.h"
#import "STServerSelectionError.h"
#import "STServerSelection.h"
#import "STLatencyMethod.h"
#import "STConnectionType.h"
#import "STThroughputStage.h"
#import "STLogLevel.h"
