// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni

// SpeedtestSDKVideo_Bridging_Header.h
// SpeedtestSDKVideo_Bridging_Header

#import <Foundation/Foundation.h>

//! Project version number for SpeedtestSDKVideoBridgingHeader.
FOUNDATION_EXPORT double SpeedtestSDKVideoBridgingHeaderVersionNumber;

//! Project version string for SpeedtestSDKVideoBridgingHeader.
FOUNDATION_EXPORT const unsigned char SpeedtestSDKVideoBridgingHeaderVersionString[];

#import "STVideoTestState.h"
#import "STVideoTestStageState.h"
#import "STVideoTestStage.h"
#import "STVideoTestStageType.h"
#import "STVideoTestStageRendition.h"
#import "STVideoTestError.h"
#import "STVideoTestErrorType.h"
#import "STVideoSuiteResult.h"
#import "STVideoStageResult.h"
#import "STAssetUrl.h"
#import "STVideoPlayerEventWithTime.h"
#import "STVideoPlayerEvent.h"
#import "STVideoPlayerEventType.h"
#import "STTimeout.h"
#import "STVideoStageError.h"
#import "STVideoStageErrorType.h"
#import "STVideoStageSubError.h"
#import "STVideoTestEndState.h"
#import "STVideoTestResolution.h"
