// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni

// SpeedtestSDKHandler_Bridging_Header.h
// SpeedtestSDKHandler_Bridging_Header

#import <Foundation/Foundation.h>

//! Project version number for SpeedtestSDKHandlerBridgingHeader.
FOUNDATION_EXPORT double SpeedtestSDKHandlerBridgingHeaderVersionNumber;

//! Project version string for SpeedtestSDKHandlerBridgingHeader.
FOUNDATION_EXPORT const unsigned char SpeedtestSDKHandlerBridgingHeaderVersionString[];

#import "STTaskManagerController.h"
#import "STTestHandler.h"
#import "STSchedulerHandler.h"
#import "STLogHandler.h"
