// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from model.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, STConnectionType)
{
    STConnectionTypeUnknown = 0,
    STConnectionTypeCellular = 1,
    STConnectionTypeWifi = 2,
    STConnectionTypeEthernet = 3,
    STConnectionTypeBluetooth = 4,
};
