// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from model.djinni

#import <Foundation/Foundation.h>

@interface STInterfaceInfo : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithIp:(nonnull NSString *)ip
                           macaddr:(nonnull NSString *)macaddr
                              name:(nonnull NSString *)name NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)InterfaceInfoWithIp:(nonnull NSString *)ip
                                    macaddr:(nonnull NSString *)macaddr
                                       name:(nonnull NSString *)name;

@property (nonatomic, readonly, nonnull) NSString * ip;

@property (nonatomic, readonly, nonnull) NSString * macaddr;

@property (nonatomic, readonly, nonnull) NSString * name;

@end
