// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from model.djinni

#import "STInterfaceInfo.h"
#import <Foundation/Foundation.h>

@interface STIpInfo : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithInternal:(nonnull STInterfaceInfo *)internal
                              externalIp:(nonnull NSString *)externalIp NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)IpInfoWithInternal:(nonnull STInterfaceInfo *)internal
                                externalIp:(nonnull NSString *)externalIp;

@property (nonatomic, readonly, nonnull) STInterfaceInfo * internal;

@property (nonatomic, readonly, nonnull) NSString * externalIp;

@end
