// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from model.djinni

#import <Foundation/Foundation.h>

/** The final result which consists of the minimum latency recorded */
@interface STLatencyResult : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithLatencyMillis:(int64_t)latencyMillis
                                 jitterMillis:(int64_t)jitterMillis NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)LatencyResultWithLatencyMillis:(int64_t)latencyMillis
                                          jitterMillis:(int64_t)jitterMillis;

@property (nonatomic, readonly) int64_t latencyMillis;

@property (nonatomic, readonly) int64_t jitterMillis;

@end
