// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from model.djinni

#import <Foundation/Foundation.h>

@interface STServer : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithId:(int64_t)id
                               url:(nonnull NSString *)url
                          hostname:(nonnull NSString *)hostname
                              port:(int32_t)port
                           sponsor:(nonnull NSString *)sponsor
                              city:(nonnull NSString *)city
                           country:(nonnull NSString *)country NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)ServerWithId:(int64_t)id
                                 url:(nonnull NSString *)url
                            hostname:(nonnull NSString *)hostname
                                port:(int32_t)port
                             sponsor:(nonnull NSString *)sponsor
                                city:(nonnull NSString *)city
                             country:(nonnull NSString *)country;

@property (nonatomic, readonly) int64_t id;

@property (nonatomic, readonly, nonnull) NSString * url;

@property (nonatomic, readonly, nonnull) NSString * hostname;

@property (nonatomic, readonly) int32_t port;

/** Server sponsor name */
@property (nonatomic, readonly, nonnull) NSString * sponsor;

/** Server host location city */
@property (nonatomic, readonly, nonnull) NSString * city;

/** Server host location country */
@property (nonatomic, readonly, nonnull) NSString * country;

@end
