// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from model.djinni

#import "STIpInfo.h"
#import "STServer.h"
#import "STServerSelectionError.h"
#import <Foundation/Foundation.h>

@interface STServerSelection : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithServer:(nonnull STServer *)server
                              serverIp:(nonnull NSString *)serverIp
                         latencyMillis:(double)latencyMillis
                                ipInfo:(nonnull STIpInfo *)ipInfo
                                 error:(nullable STServerSelectionError *)error NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)ServerSelectionWithServer:(nonnull STServer *)server
                                         serverIp:(nonnull NSString *)serverIp
                                    latencyMillis:(double)latencyMillis
                                           ipInfo:(nonnull STIpInfo *)ipInfo
                                            error:(nullable STServerSelectionError *)error;

@property (nonatomic, readonly, nonnull) STServer * server;

@property (nonatomic, readonly, nonnull) NSString * serverIp;

@property (nonatomic, readonly) double latencyMillis;

@property (nonatomic, readonly, nonnull) STIpInfo * ipInfo;

@property (nonatomic, readonly, nullable) STServerSelectionError * error;

@end
