// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sdk.djinni

#import "STTaskStatusReason.h"
#import <Foundation/Foundation.h>

@interface STTaskStatus : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithStart:(BOOL)start
                               reason:(STTaskStatusReason)reason
                              message:(nullable NSString *)message NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)TaskStatusWithStart:(BOOL)start
                                     reason:(STTaskStatusReason)reason
                                    message:(nullable NSString *)message;

/** will be set to false if the task could not be started */
@property (nonatomic, readonly) BOOL start;

/** Started if task was started, otherwise the reason it was not */
@property (nonatomic, readonly) STTaskStatusReason reason;

/** if isStarted is false, this will contain the reason */
@property (nonatomic, readonly, nullable) NSString * message;

@end
