// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sdk.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, STTaskStatusReason)
{
    STTaskStatusReasonStarted = 0,
    STTaskStatusReasonAlreadyRunning = 1,
    STTaskStatusReasonDeferred = 2,
    STTaskStatusReasonInvalidState = 3,
};
