// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from video.djinni

#import <Foundation/Foundation.h>

/** Type of timeout. */
typedef NS_ENUM(NSInteger, STTimeout)
{
    /** Stage timed out before the first frame rendered. */
    STTimeoutLoading = 0,
    /** Stage timed out while stalled after the first frame rendered. */
    STTimeoutPlayback = 1,
};
