// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from video.djinni

#import <Foundation/Foundation.h>

/** State of the test when it ended. */
typedef NS_ENUM(NSInteger, STVideoTestEndState)
{
    /** The test was in the configuration stage, before any stage got to run. */
    STVideoTestEndStateConfiguring = 0,
    /** The test was running the stages. */
    STVideoTestEndStateStages = 1,
    /** The test was done running the stages. */
    STVideoTestEndStateComplete = 2,
};
