// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from video.djinni

#import "STVideoPlayerEvent.h"
#import <Foundation/Foundation.h>

/** Combination of a video player event with the time during which it happened. */
@interface STVideoPlayerEventWithTime : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithTime:(int64_t)time
                               event:(nonnull STVideoPlayerEvent *)event NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)VideoPlayerEventWithTimeWithTime:(int64_t)time
                                                   event:(nonnull STVideoPlayerEvent *)event;

/** The time of the event. */
@property (nonatomic, readonly) int64_t time;

/** The actual video player event. */
@property (nonatomic, readonly, nonnull) STVideoPlayerEvent * event;

@end
