// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from video.djinni

#import "STVideoTestErrorType.h"
#import <Foundation/Foundation.h>

/** Error that occurred during a video test. */
@interface STVideoTestError : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithMessage:(nonnull NSString *)message
                                   type:(STVideoTestErrorType)type NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)VideoTestErrorWithMessage:(nonnull NSString *)message
                                             type:(STVideoTestErrorType)type;

/** Message describing the error. */
@property (nonatomic, readonly, nonnull) NSString * message;

/** The type of error that occurred during the video test. */
@property (nonatomic, readonly) STVideoTestErrorType type;

@end
