// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from video.djinni

#import <Foundation/Foundation.h>

/** Error description as a string. */
@interface STVideoStageSubError : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithMessage:(nullable NSString *)message NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)VideoStageSubErrorWithMessage:(nullable NSString *)message;

@property (nonatomic, readonly, nullable) NSString * message;

@end
