// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from video.djinni

#import "STVideoTestResolution.h"
#import <Foundation/Foundation.h>

/** Rendition of a Fixed stage. */
@interface STVideoTestStageRendition : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithName:(nonnull NSString *)name
                         displayName:(nonnull NSString *)displayName
                             bitrate:(int32_t)bitrate
                          resolution:(nonnull STVideoTestResolution *)resolution NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)VideoTestStageRenditionWithName:(nonnull NSString *)name
                                            displayName:(nonnull NSString *)displayName
                                                bitrate:(int32_t)bitrate
                                             resolution:(nonnull STVideoTestResolution *)resolution;

/** Name of the rendition as configured. */
@property (nonatomic, readonly, nonnull) NSString * name;

/** Display name of the stage as configured. */
@property (nonatomic, readonly, nonnull) NSString * displayName;

/** Bitrate of the stage. */
@property (nonatomic, readonly) int32_t bitrate;

/** Resolution of the rendition. */
@property (nonatomic, readonly, nonnull) STVideoTestResolution * resolution;

@end
