// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni

// SpeedtestSDK_Bridging_Header.h
// SpeedtestSDK_Bridging_Header

#import <Foundation/Foundation.h>

//! Project version number for SpeedtestSDKBridgingHeader.
FOUNDATION_EXPORT double SpeedtestSDKBridgingHeaderVersionNumber;

//! Project version string for SpeedtestSDKBridgingHeader.
FOUNDATION_EXPORT const unsigned char SpeedtestSDKBridgingHeaderVersionString[];

#import "STTaskManagerCreateStatus.h"
#import "STTaskManager.h"
#import "STTaskStatus.h"
#import "STTaskStatusReason.h"
#import "STScheduler.h"
