// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni

// SpeedtestSDKConfig_Bridging_Header.h
// SpeedtestSDKConfig_Bridging_Header

#import <Foundation/Foundation.h>

//! Project version number for SpeedtestSDKConfigBridgingHeader.
FOUNDATION_EXPORT double SpeedtestSDKConfigBridgingHeaderVersionNumber;

//! Project version string for SpeedtestSDKConfigBridgingHeader.
FOUNDATION_EXPORT const unsigned char SpeedtestSDKConfigBridgingHeaderVersionString[];

#import "STTrigger.h"
#import "STValidatedConfig.h"
#import "STConfig.h"
#import "STCoverageTriggerConfig.h"
#import "STConfigHandler.h"
#import "STSaver.h"
#import "STTask.h"
#import "STLocalJobStatus.h"
