// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from video.djinni

#import <Foundation/Foundation.h>

/** URL record of an asset. */
@interface STAssetUrl : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithName:(nonnull NSString *)name
                         displayName:(nonnull NSString *)displayName
                                 url:(nonnull NSString *)url NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)AssetUrlWithName:(nonnull NSString *)name
                             displayName:(nonnull NSString *)displayName
                                     url:(nonnull NSString *)url;

/** Identifier of the asset URL. */
@property (nonatomic, readonly, nonnull) NSString * name;

/** Display name of the asset URL. */
@property (nonatomic, readonly, nonnull) NSString * displayName;

/** URL of the asset. */
@property (nonatomic, readonly, nonnull) NSString * url;

@end
