// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from config.djinni

#import "STServerSelection.h"
#import <Foundation/Foundation.h>
@class STValidatedConfig;


@protocol STConfigHandler

- (void)onConfigFetchStarted;

- (void)onConfigFetchFailedBinary:(nonnull NSData *)error;

- (void)onConfigFetchFinished:(nullable STValidatedConfig *)config;

- (void)onServerSelectionStarted;

/** Server selection finished. Selection result is attached. */
- (void)onSelectionFinished:(nonnull NSArray<STServerSelection *> *)result;

/**
 * Server selection failed due to no successful servers found. 
 * The server selection result includes all the errors. 
 */
- (void)onSelectionFailed:(nonnull NSArray<STServerSelection *> *)result;

@end
