// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from config.djinni

#import "STLatencyMethod.h"
#import <Foundation/Foundation.h>
@class STConfig;
@class STTask;


@interface STConfig : NSObject

/**
 * Create a new configuration using a named preset. The preset is created from
 * the customer portal and can be dynamically changed there. 
 */
+ (nullable STConfig *)newConfig:(nonnull NSString *)name;

- (nonnull NSString *)getName;

- (BOOL)setMinConnectionCount:(int8_t)count;

- (int8_t)getMinConnectionCount;

- (BOOL)setMaxConnectionCount:(int8_t)count;

- (int8_t)getMaxConnectionCount;

- (BOOL)setTransferTestDurationSeconds:(int8_t)seconds;

- (int8_t)getTransferTestDurationSeconds;

- (BOOL)setLatencyNumPings:(int8_t)pings;

- (int8_t)getLatencyNumPings;

- (void)setLatencyMethod:(STLatencyMethod)method;

- (STLatencyMethod)getLatencyMethod;

/** Set the server id to use for testing. If this is not a valid id, testing will fail. */
- (void)setServerIdForTesting:(int32_t)serverId;

- (int32_t)getServerIdForTesting;

/** Disable saving of results to the Ookla backend. This also prevents results from being available in extracts and similar.  */
- (void)setDisableResultUpload:(BOOL)disableUpload;

- (BOOL)getDisableResultUpload;

/**
 * Specify the tasks (upload, download, latency, traceroute, packetloss etc.)
 * that need to run as part of the test runner. 
 *
 * Default: Runs Latency, Download, Upload and Packetloss
 */
- (void)setTasks:(nonnull NSArray<STTask *> *)tasks;

/** Tasks configured using setTasks or the default set of pre-configured tasks */
- (nonnull NSArray<STTask *> *)getTasks;

/** The last time the job was triggered */
- (void)setLastRunTime:(nonnull NSDate *)lastRunTime;

- (nonnull NSDate *)getLastRunTime;

@end
