// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from model.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, STLatencyMethod)
{
    STLatencyMethodDefault = 0,
    STLatencyMethodMinimum = 1,
    STLatencyMethodMedian = 2,
    STLatencyMethodMean = 3,
    STLatencyMethodTrimmedMean = 4,
};
