// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from model.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, STLogLevel)
{
    STLogLevelError = 0,
    STLogLevelWarning = 1,
    STLogLevelInfo = 2,
    STLogLevelDebug = 3,
};
