// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from config.djinni

#import "STConnectionType.h"
#import <Foundation/Foundation.h>
@class STSaver;


@interface STSaver : NSObject

+ (nullable STSaver *)newDefaultSaver;

/** Configure immediate result upload, or not. Defaults to true which immediately submits result after task finishes execution. */
- (void)setImmediate:(BOOL)immediate;

- (BOOL)getImmediate;

/**
 * Defaults to true which obfuscates the result payload. Change this to false if 
 * submitting the result to a custom endpoint
 */
- (void)setObfuscate:(BOOL)obfuscate;

- (BOOL)getObfuscate;

/** Custom endpoint where results can be posted.  */
- (void)setUrl:(nonnull NSString *)url;

- (nonnull NSString *)getUrl;

/** Configures how many results to collect before uploading */
- (void)setBatchSize:(int32_t)batch;

- (int32_t)getBatchSize;

/** Configures how many times a result upload is retried  */
- (void)setMaxFailedAttempts:(int32_t)attempts;

- (int32_t)getMaxFailedAttempts;

/** Only uploads results when the network type is in the types list */
- (void)setAllowedConnectionTypes:(nonnull NSArray<NSNumber *> *)types;

- (nonnull NSArray<NSNumber *> *)getAllowedConnectionTypes;

@end
