// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sdk.djinni

#import "STSchedulerHandler.h"
#import <Foundation/Foundation.h>


/**
 * Once the scheduler is created, it will start running the test according to the schedule
 * and can only be canceled
 */
@protocol STScheduler

- (void)setListener:(nullable STSchedulerHandler *)handler;

- (void)cancel;

@end
