// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from handler.djinni

#import <Foundation/Foundation.h>


@interface STSchedulerHandler : NSObject

- (void)onInvoked;

- (void)onCanceled;

@end
