// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from model.djinni

#import "STServerSelectionError.h"
#import <Foundation/Foundation.h>

@interface STServerSelectionError : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithErrorCode:(int64_t)errorCode
                                  message:(nonnull NSString *)message
                                   causes:(nullable NSArray<STServerSelectionError *> *)causes NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)ServerSelectionErrorWithErrorCode:(int64_t)errorCode
                                                  message:(nonnull NSString *)message
                                                   causes:(nullable NSArray<STServerSelectionError *> *)causes;

@property (nonatomic, readonly) int64_t errorCode;

@property (nonatomic, readonly, nonnull) NSString * message;

@property (nonatomic, readonly, nullable) NSArray<STServerSelectionError *> * causes;

@end
