// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from handler.djinni

#import <Foundation/Foundation.h>


@interface STTaskManagerController : NSObject

/** Cancel all the tasks and stop the test. */
- (void)cancel;

/** Supplemental Data contains extra json info that will become a part of the result json with the key "supplementalData". */
- (BOOL)setSupplementalData:(nonnull NSData *)data;

@end
