// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sdk.djinni

#import <Foundation/Foundation.h>
@class STTaskManager;


/**
 * Encapsulates the creation of a task manager and lets the caller know whether
 * the task manager already existed or was created
 */
@interface STTaskManagerCreateStatus : NSObject

/** true if a background task was already created in the past */
- (BOOL)didExist;

/** either the newly created task manager or the existing one */
- (nullable STTaskManager *)getTaskManager;

@end
