// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from model.djinni

#import <Foundation/Foundation.h>

/** The different stages for a throughput task. Each can be run on its own or combined */
typedef NS_ENUM(NSInteger, STThroughputStage)
{
    /**
     * Latency is the reaction time of your connection–how quickly your device gets 
     * a response after you've sent out a request
     * Additional details: https://www.speedtest.net/about/knowledge/glossary
     */
    STThroughputStageLatency = 0,
    /**
     * Measures how quickly you can pull data from a server on the internet to your device
     * Additional details: https://www.speedtest.net/about/knowledge/glossary
     */
    STThroughputStageDownload = 1,
    /**
     * Measures how quickly you can pull data from a server on the internet to your device
     * Additional details: https://www.speedtest.net/about/knowledge/glossary
     */
    STThroughputStageHttpDownload = 2,
    /**
     * Measures how quickly you send data from your device to the internet
     *
     */
    STThroughputStageUpload = 3,
    /**
     * Before any testing can be done, a configuration load might occur. If that 
     * happens, an error is returned for this stage. 
     */
    STThroughputStageConfigLoad = 4,
};
