// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from model.djinni

#import <Foundation/Foundation.h>

/** Represents the results of a transfer in progress */
@interface STTransferResult : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithBytes:(int64_t)bytes
                       durationMillis:(double)durationMillis
                            speedMbps:(double)speedMbps NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)TransferResultWithBytes:(int64_t)bytes
                                 durationMillis:(double)durationMillis
                                      speedMbps:(double)speedMbps;

@property (nonatomic, readonly) int64_t bytes;

@property (nonatomic, readonly) double durationMillis;

@property (nonatomic, readonly) double speedMbps;

@end
