// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from video.djinni

#import <Foundation/Foundation.h>

/** Type of stage the video test is currently running. */
typedef NS_ENUM(NSInteger, STVideoTestStageType)
{
    /** Adaptive bit rate stage. */
    STVideoTestStageTypeAdaptive = 0,
    /** Fixed bit rate stage. */
    STVideoTestStageTypeFixed = 1,
};
