// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from video.djinni

#import "STVideoStageErrorType.h"
#import "STVideoStageSubError.h"
#import <Foundation/Foundation.h>

/** Error for a video stage. */
@interface STVideoStageError : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithType:(nullable NSNumber *)type
                             message:(nullable NSString *)message
                           suberrors:(nullable NSArray<STVideoStageSubError *> *)suberrors NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)VideoStageErrorWithType:(nullable NSNumber *)type
                                        message:(nullable NSString *)message
                                      suberrors:(nullable NSArray<STVideoStageSubError *> *)suberrors;

/** The type of error. */
@property (nonatomic, readonly, nullable) NSNumber * type;

/** Message attached to the error, if any. */
@property (nonatomic, readonly, nullable) NSString * message;

/** Any sub-errors that could have caused the error. */
@property (nonatomic, readonly, nullable) NSArray<STVideoStageSubError *> * suberrors;

@end
