// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from video.djinni

#import "STVideoTestStageState.h"
#import <Foundation/Foundation.h>

/** The state of a running video test. */
@interface STVideoTestState : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithStageState:(nonnull STVideoTestStageState *)stageState
                                  progress:(float)progress NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)VideoTestStateWithStageState:(nonnull STVideoTestStageState *)stageState
                                            progress:(float)progress;

/** Information about the stage that's currently running. */
@property (nonatomic, readonly, nonnull) STVideoTestStageState * stageState;

/** Overall progress of the test. */
@property (nonatomic, readonly) float progress;

@end
