// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from video.djinni

#import "STVideoStageResult.h"
#import "STVideoTestEndState.h"
#import <Foundation/Foundation.h>

/** Result of a video test. */
@interface STVideoSuiteResult : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithVideoStageResult:(nonnull NSArray<STVideoStageResult *> *)videoStageResult
                                  videoTestState:(STVideoTestEndState)videoTestState
                               maximumResolution:(nonnull NSString *)maximumResolution
                             abrBufferPercentage:(nonnull NSArray<NSNumber *> *)abrBufferPercentage NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)VideoSuiteResultWithVideoStageResult:(nonnull NSArray<STVideoStageResult *> *)videoStageResult
                                              videoTestState:(STVideoTestEndState)videoTestState
                                           maximumResolution:(nonnull NSString *)maximumResolution
                                         abrBufferPercentage:(nonnull NSArray<NSNumber *> *)abrBufferPercentage;

/** Results for every individual stage. */
@property (nonatomic, readonly, nonnull) NSArray<STVideoStageResult *> * videoStageResult;

/** The state of the video test at the end of the test. */
@property (nonatomic, readonly) STVideoTestEndState videoTestState;

/** Maximum resolution. */
@property (nonatomic, readonly, nonnull) NSString * maximumResolution;

/** Buffer percentages of the Adaptive stages. */
@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * abrBufferPercentage;

@end
