// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from video.djinni

#import <Foundation/Foundation.h>

/** Type of video test error. */
typedef NS_ENUM(NSInteger, STVideoTestErrorType)
{
    /** The supplied configuration was invalid. */
    STVideoTestErrorTypeInvalidConfig = 0,
    /** The player could not be created. Did you set a `STVideoTestView`? */
    STVideoTestErrorTypeVideoPlayerCreationFailed = 1,
    /** An error happened while playing the video. */
    STVideoTestErrorTypeVideoPlayerPlayback = 2,
    /** Error used for platform specific initialization errors. Currently unused. */
    STVideoTestErrorTypeVideoPlayerSetup = 3,
    /** Timeout fired before the first frame was rendered. */
    STVideoTestErrorTypeVideoPlayerLoadTimeout = 4,
    /** Timeout fired while the test stalled after the first frame was rendered. */
    STVideoTestErrorTypeVideoPlayerStallTimeout = 5,
    /** Error used for platform specific playback errors. */
    STVideoTestErrorTypeVideoMediaCodecException = 6,
    /** Error formerly thrown when a stage is missing. Currently unused, see `STinvalidConfig`. */
    STVideoTestErrorTypeVideoTestStageMissing = 7,
    /** Error used for network errors signalled before stage driven timeouts. */
    STVideoTestErrorTypeVideoPlayerNetworkError = 8,
    /** Deprecated. Don't use this, a VideoTestError will never be of this type. Use `STuserBackground` instead. */
    STVideoTestErrorTypeUserBackgrounded = 9,
    /** The user backgrounded the application. */
    STVideoTestErrorTypeUserBackground = 10,
};
