// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from video.djinni

#import "STAssetUrl.h"
#import "STVideoTestStage.h"
#import <Foundation/Foundation.h>

/** Encapsulates information about a running stage. */
@interface STVideoTestStageState : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithStage:(nonnull STVideoTestStage *)stage
                                  url:(nonnull STAssetUrl *)url
                      firstFrameShown:(BOOL)firstFrameShown
                              loading:(BOOL)loading NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)VideoTestStageStateWithStage:(nonnull STVideoTestStage *)stage
                                                 url:(nonnull STAssetUrl *)url
                                     firstFrameShown:(BOOL)firstFrameShown
                                             loading:(BOOL)loading;

/** The stage that's running. */
@property (nonatomic, readonly, nonnull) STVideoTestStage * stage;

/** The asset url for the video the stage will play. */
@property (nonatomic, readonly, nonnull) STAssetUrl * url;

/** Whether the first frame has been shown. */
@property (nonatomic, readonly) BOOL firstFrameShown;

/** Whether the stage is loading (true when stalled). */
@property (nonatomic, readonly) BOOL loading;

@end
