{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ookla.speedtest.sdk",
    "module": "speedtest-sdk",
    "version": "3.3.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "speedtest-sdk-3.3.1.10.aar",
          "url": "speedtest-sdk-3.3.1.10.aar",
          "size": 8354551,
          "sha512": "8bb464311cbaea2a44566f3a988bc4c55db1b9bc01f7b2ea25a90219be4d77c8e2be55ea6e4f39aa3c85ff4074e78cdd64ade3111921fe6cb3d1f64de3c60964",
          "sha256": "36de3da633c8e64341102594ce85051522e7259e38d407920c9b0f02cbe34792",
          "sha1": "73bc4dbedce170756d294af5b05ec9063aaa1112",
          "md5": "9c8132e1816ec742e0d293320e4e7f8f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-analytics",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.getkeepsafe.relinker",
          "module": "relinker",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "de.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "speedtest-sdk-3.3.1.10.aar",
          "url": "speedtest-sdk-3.3.1.10.aar",
          "size": 8354551,
          "sha512": "8bb464311cbaea2a44566f3a988bc4c55db1b9bc01f7b2ea25a90219be4d77c8e2be55ea6e4f39aa3c85ff4074e78cdd64ade3111921fe6cb3d1f64de3c60964",
          "sha256": "36de3da633c8e64341102594ce85051522e7259e38d407920c9b0f02cbe34792",
          "sha1": "73bc4dbedce170756d294af5b05ec9063aaa1112",
          "md5": "9c8132e1816ec742e0d293320e4e7f8f"
        }
      ]
    }
  ]
}
